/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sYXMYndb1v9rTXALzdZyn1
// Component: RRo5SJwz2Sbr

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button from "../../Button"; // plasmic-import: -BkoXfQ_mA7-/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: sYXMYndb1v9rTXALzdZyn1/projectcss
import sty from "./PlasmicAddEndo.module.css"; // plasmic-import: RRo5SJwz2Sbr/css

import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: Yw1_HV9alQRc/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: AFWtWFpVw7kz/icon

createPlasmicElementProxy;

export type PlasmicAddEndo__VariantMembers = {};
export type PlasmicAddEndo__VariantsArgs = {};
type VariantPropType = keyof PlasmicAddEndo__VariantsArgs;
export const PlasmicAddEndo__VariantProps = new Array<VariantPropType>();

export type PlasmicAddEndo__ArgsType = {
  submissionEndometriome?: any;
  onSubmissionEndometriomeChange?: (val: string) => void;
};
type ArgPropType = keyof PlasmicAddEndo__ArgsType;
export const PlasmicAddEndo__ArgProps = new Array<ArgPropType>(
  "submissionEndometriome",
  "onSubmissionEndometriomeChange"
);

export type PlasmicAddEndo__OverridesType = {
  addEnd?: Flex__<typeof Button>;
  text?: Flex__<"div">;
};

export interface DefaultAddEndoProps {
  submissionEndometriome?: any;
  onSubmissionEndometriomeChange?: (val: string) => void;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAddEndo__RenderFunc(props: {
  variants: PlasmicAddEndo__VariantsArgs;
  args: PlasmicAddEndo__ArgsType;
  overrides: PlasmicAddEndo__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "addEnd.shape",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => "round"
      },
      {
        path: "submissionEndometriome",
        type: "writable",
        variableType: "array",

        valueProp: "submissionEndometriome",
        onChangeProp: "onSubmissionEndometriomeChange"
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <Button
      data-plasmic-name={"addEnd"}
      data-plasmic-override={overrides.addEnd}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames("__wab_instance", sty.addEnd)}
      onClick={async event => {
        const $steps = {};
      }}
      onShapeChange={async (...eventArgs: any) => {
        ((...eventArgs) => {
          generateStateOnChangeProp($state, ["addEnd", "shape"])(eventArgs[0]);
        }).apply(null, eventArgs);

        if (
          eventArgs.length > 1 &&
          eventArgs[1] &&
          eventArgs[1]._plasmic_state_init_
        ) {
          return;
        }
      }}
      shape={generateStateValueProp($state, ["addEnd", "shape"])}
    >
      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text)}
      >
        {"Button"}
      </div>
    </Button>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  addEnd: ["addEnd", "text"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  addEnd: typeof Button;
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAddEndo__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAddEndo__VariantsArgs;
    args?: PlasmicAddEndo__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicAddEndo__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicAddEndo__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAddEndo__ArgProps,
          internalVariantPropNames: PlasmicAddEndo__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAddEndo__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "addEnd") {
    func.displayName = "PlasmicAddEndo";
  } else {
    func.displayName = `PlasmicAddEndo.${nodeName}`;
  }
  return func;
}

export const PlasmicAddEndo = Object.assign(
  // Top-level PlasmicAddEndo renders the root element
  makeNodeComponent("addEnd"),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicAddEndo
    internalVariantProps: PlasmicAddEndo__VariantProps,
    internalArgProps: PlasmicAddEndo__ArgProps
  }
);

export default PlasmicAddEndo;
/* prettier-ignore-end */
