/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jND4haQkMjdpXVH9tN144R
// Component: QgqOMf83NXMp

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import BtmNavbarTile from "../../BtmNavbarTile"; // plasmic-import: BsSasfqP5JtI/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: jND4haQkMjdpXVH9tN144R/projectcss
import sty from "./PlasmicBtmNavbar.module.css"; // plasmic-import: QgqOMf83NXMp/css

createPlasmicElementProxy;

export type PlasmicBtmNavbar__VariantMembers = {};
export type PlasmicBtmNavbar__VariantsArgs = {};
type VariantPropType = keyof PlasmicBtmNavbar__VariantsArgs;
export const PlasmicBtmNavbar__VariantProps = new Array<VariantPropType>();

export type PlasmicBtmNavbar__ArgsType = {};
type ArgPropType = keyof PlasmicBtmNavbar__ArgsType;
export const PlasmicBtmNavbar__ArgProps = new Array<ArgPropType>();

export type PlasmicBtmNavbar__OverridesType = {
  frame1437254343?: Flex__<"div">;
  btmNavbarTile?: Flex__<typeof BtmNavbarTile>;
  phGridFourFill19?: Flex__<"div">;
  rectangle74?: Flex__<"div">;
  rectangle75?: Flex__<"div">;
  rectangle76?: Flex__<"div">;
  phGridFourFill20?: Flex__<"div">;
  rectangle77?: Flex__<"div">;
  rectangle78?: Flex__<"div">;
  rectangle79?: Flex__<"div">;
  phGridFourFill21?: Flex__<"div">;
  rectangle80?: Flex__<"div">;
  rectangle81?: Flex__<"div">;
  rectangle82?: Flex__<"div">;
  btmNavbarTile7?: Flex__<typeof BtmNavbarTile>;
  phGridFourFill37?: Flex__<"div">;
  rectangle128?: Flex__<"div">;
  rectangle129?: Flex__<"div">;
  rectangle130?: Flex__<"div">;
  phGridFourFill38?: Flex__<"div">;
  rectangle131?: Flex__<"div">;
  rectangle132?: Flex__<"div">;
  rectangle133?: Flex__<"div">;
  phGridFourFill39?: Flex__<"div">;
  rectangle134?: Flex__<"div">;
  rectangle135?: Flex__<"div">;
  rectangle136?: Flex__<"div">;
  btmNavbarTile6?: Flex__<typeof BtmNavbarTile>;
  phGridFourFill34?: Flex__<"div">;
  rectangle119?: Flex__<"div">;
  rectangle120?: Flex__<"div">;
  rectangle121?: Flex__<"div">;
  phGridFourFill35?: Flex__<"div">;
  rectangle122?: Flex__<"div">;
  rectangle123?: Flex__<"div">;
  rectangle124?: Flex__<"div">;
  phGridFourFill36?: Flex__<"div">;
  rectangle125?: Flex__<"div">;
  rectangle126?: Flex__<"div">;
  rectangle127?: Flex__<"div">;
  btmNavbarTile5?: Flex__<typeof BtmNavbarTile>;
  phGridFourFill31?: Flex__<"div">;
  rectangle110?: Flex__<"div">;
  rectangle111?: Flex__<"div">;
  rectangle112?: Flex__<"div">;
  phGridFourFill32?: Flex__<"div">;
  rectangle113?: Flex__<"div">;
  rectangle114?: Flex__<"div">;
  rectangle115?: Flex__<"div">;
  phGridFourFill33?: Flex__<"div">;
  rectangle116?: Flex__<"div">;
  rectangle117?: Flex__<"div">;
  rectangle118?: Flex__<"div">;
  btmNavbarTile4?: Flex__<typeof BtmNavbarTile>;
  phGridFourFill28?: Flex__<"div">;
  rectangle101?: Flex__<"div">;
  rectangle102?: Flex__<"div">;
  rectangle103?: Flex__<"div">;
  phGridFourFill29?: Flex__<"div">;
  rectangle104?: Flex__<"div">;
  rectangle105?: Flex__<"div">;
  rectangle106?: Flex__<"div">;
  phGridFourFill30?: Flex__<"div">;
  rectangle107?: Flex__<"div">;
  rectangle108?: Flex__<"div">;
  rectangle109?: Flex__<"div">;
  btmNavbarTile3?: Flex__<typeof BtmNavbarTile>;
  phGridFourFill25?: Flex__<"div">;
  rectangle92?: Flex__<"div">;
  rectangle93?: Flex__<"div">;
  rectangle94?: Flex__<"div">;
  phGridFourFill26?: Flex__<"div">;
  rectangle95?: Flex__<"div">;
  rectangle96?: Flex__<"div">;
  rectangle97?: Flex__<"div">;
  phGridFourFill27?: Flex__<"div">;
  rectangle98?: Flex__<"div">;
  rectangle99?: Flex__<"div">;
  rectangle100?: Flex__<"div">;
  btmNavbarTile2?: Flex__<typeof BtmNavbarTile>;
};

export interface DefaultBtmNavbarProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicBtmNavbar__RenderFunc(props: {
  variants: PlasmicBtmNavbar__VariantsArgs;
  args: PlasmicBtmNavbar__ArgsType;
  overrides: PlasmicBtmNavbar__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <div
      data-plasmic-name={"frame1437254343"}
      data-plasmic-override={overrides.frame1437254343}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.frame1437254343
      )}
    >
      <BtmNavbarTile
        data-plasmic-name={"btmNavbarTile"}
        data-plasmic-override={overrides.btmNavbarTile}
        className={classNames("__wab_instance", sty.btmNavbarTile)}
        frame1437254298={
          <React.Fragment>
            <Stack__
              as={"div"}
              data-plasmic-name={"phGridFourFill19"}
              data-plasmic-override={overrides.phGridFourFill19}
              hasGap={true}
              className={classNames(projectcss.all, sty.phGridFourFill19)}
            >
              <div
                data-plasmic-name={"rectangle74"}
                data-plasmic-override={overrides.rectangle74}
                className={classNames(projectcss.all, sty.rectangle74)}
              />

              <div
                data-plasmic-name={"rectangle75"}
                data-plasmic-override={overrides.rectangle75}
                className={classNames(projectcss.all, sty.rectangle75)}
              />

              <div
                data-plasmic-name={"rectangle76"}
                data-plasmic-override={overrides.rectangle76}
                className={classNames(projectcss.all, sty.rectangle76)}
              />
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"phGridFourFill20"}
              data-plasmic-override={overrides.phGridFourFill20}
              hasGap={true}
              className={classNames(projectcss.all, sty.phGridFourFill20)}
            >
              <div
                data-plasmic-name={"rectangle77"}
                data-plasmic-override={overrides.rectangle77}
                className={classNames(projectcss.all, sty.rectangle77)}
              />

              <div
                data-plasmic-name={"rectangle78"}
                data-plasmic-override={overrides.rectangle78}
                className={classNames(projectcss.all, sty.rectangle78)}
              />

              <div
                data-plasmic-name={"rectangle79"}
                data-plasmic-override={overrides.rectangle79}
                className={classNames(projectcss.all, sty.rectangle79)}
              />
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"phGridFourFill21"}
              data-plasmic-override={overrides.phGridFourFill21}
              hasGap={true}
              className={classNames(projectcss.all, sty.phGridFourFill21)}
            >
              <div
                data-plasmic-name={"rectangle80"}
                data-plasmic-override={overrides.rectangle80}
                className={classNames(projectcss.all, sty.rectangle80)}
              />

              <div
                data-plasmic-name={"rectangle81"}
                data-plasmic-override={overrides.rectangle81}
                className={classNames(projectcss.all, sty.rectangle81)}
              />

              <div
                data-plasmic-name={"rectangle82"}
                data-plasmic-override={overrides.rectangle82}
                className={classNames(projectcss.all, sty.rectangle82)}
              />
            </Stack__>
          </React.Fragment>
        }
      >
        {"AC"}
      </BtmNavbarTile>
      <BtmNavbarTile
        data-plasmic-name={"btmNavbarTile7"}
        data-plasmic-override={overrides.btmNavbarTile7}
        className={classNames("__wab_instance", sty.btmNavbarTile7)}
        frame1437254298={
          <React.Fragment>
            <Stack__
              as={"div"}
              data-plasmic-name={"phGridFourFill37"}
              data-plasmic-override={overrides.phGridFourFill37}
              hasGap={true}
              className={classNames(projectcss.all, sty.phGridFourFill37)}
            >
              <div
                data-plasmic-name={"rectangle128"}
                data-plasmic-override={overrides.rectangle128}
                className={classNames(projectcss.all, sty.rectangle128)}
              />

              <div
                data-plasmic-name={"rectangle129"}
                data-plasmic-override={overrides.rectangle129}
                className={classNames(projectcss.all, sty.rectangle129)}
              />

              <div
                data-plasmic-name={"rectangle130"}
                data-plasmic-override={overrides.rectangle130}
                className={classNames(projectcss.all, sty.rectangle130)}
              />
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"phGridFourFill38"}
              data-plasmic-override={overrides.phGridFourFill38}
              hasGap={true}
              className={classNames(projectcss.all, sty.phGridFourFill38)}
            >
              <div
                data-plasmic-name={"rectangle131"}
                data-plasmic-override={overrides.rectangle131}
                className={classNames(projectcss.all, sty.rectangle131)}
              />

              <div
                data-plasmic-name={"rectangle132"}
                data-plasmic-override={overrides.rectangle132}
                className={classNames(projectcss.all, sty.rectangle132)}
              />

              <div
                data-plasmic-name={"rectangle133"}
                data-plasmic-override={overrides.rectangle133}
                className={classNames(projectcss.all, sty.rectangle133)}
              />
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"phGridFourFill39"}
              data-plasmic-override={overrides.phGridFourFill39}
              hasGap={true}
              className={classNames(projectcss.all, sty.phGridFourFill39)}
            >
              <div
                data-plasmic-name={"rectangle134"}
                data-plasmic-override={overrides.rectangle134}
                className={classNames(projectcss.all, sty.rectangle134)}
              />

              <div
                data-plasmic-name={"rectangle135"}
                data-plasmic-override={overrides.rectangle135}
                className={classNames(projectcss.all, sty.rectangle135)}
              />

              <div
                data-plasmic-name={"rectangle136"}
                data-plasmic-override={overrides.rectangle136}
                className={classNames(projectcss.all, sty.rectangle136)}
              />
            </Stack__>
          </React.Fragment>
        }
      >
        {"MC"}
      </BtmNavbarTile>
      <BtmNavbarTile
        data-plasmic-name={"btmNavbarTile6"}
        data-plasmic-override={overrides.btmNavbarTile6}
        className={classNames("__wab_instance", sty.btmNavbarTile6)}
        frame1437254298={
          <React.Fragment>
            <Stack__
              as={"div"}
              data-plasmic-name={"phGridFourFill34"}
              data-plasmic-override={overrides.phGridFourFill34}
              hasGap={true}
              className={classNames(projectcss.all, sty.phGridFourFill34)}
            >
              <div
                data-plasmic-name={"rectangle119"}
                data-plasmic-override={overrides.rectangle119}
                className={classNames(projectcss.all, sty.rectangle119)}
              />

              <div
                data-plasmic-name={"rectangle120"}
                data-plasmic-override={overrides.rectangle120}
                className={classNames(projectcss.all, sty.rectangle120)}
              />

              <div
                data-plasmic-name={"rectangle121"}
                data-plasmic-override={overrides.rectangle121}
                className={classNames(projectcss.all, sty.rectangle121)}
              />
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"phGridFourFill35"}
              data-plasmic-override={overrides.phGridFourFill35}
              hasGap={true}
              className={classNames(projectcss.all, sty.phGridFourFill35)}
            >
              <div
                data-plasmic-name={"rectangle122"}
                data-plasmic-override={overrides.rectangle122}
                className={classNames(projectcss.all, sty.rectangle122)}
              />

              <div
                data-plasmic-name={"rectangle123"}
                data-plasmic-override={overrides.rectangle123}
                className={classNames(projectcss.all, sty.rectangle123)}
              />

              <div
                data-plasmic-name={"rectangle124"}
                data-plasmic-override={overrides.rectangle124}
                className={classNames(projectcss.all, sty.rectangle124)}
              />
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"phGridFourFill36"}
              data-plasmic-override={overrides.phGridFourFill36}
              hasGap={true}
              className={classNames(projectcss.all, sty.phGridFourFill36)}
            >
              <div
                data-plasmic-name={"rectangle125"}
                data-plasmic-override={overrides.rectangle125}
                className={classNames(projectcss.all, sty.rectangle125)}
              />

              <div
                data-plasmic-name={"rectangle126"}
                data-plasmic-override={overrides.rectangle126}
                className={classNames(projectcss.all, sty.rectangle126)}
              />

              <div
                data-plasmic-name={"rectangle127"}
                data-plasmic-override={overrides.rectangle127}
                className={classNames(projectcss.all, sty.rectangle127)}
              />
            </Stack__>
          </React.Fragment>
        }
      >
        {"PC"}
      </BtmNavbarTile>
      <BtmNavbarTile
        data-plasmic-name={"btmNavbarTile5"}
        data-plasmic-override={overrides.btmNavbarTile5}
        className={classNames("__wab_instance", sty.btmNavbarTile5)}
        frame1437254298={
          <React.Fragment>
            <Stack__
              as={"div"}
              data-plasmic-name={"phGridFourFill31"}
              data-plasmic-override={overrides.phGridFourFill31}
              hasGap={true}
              className={classNames(projectcss.all, sty.phGridFourFill31)}
            >
              <div
                data-plasmic-name={"rectangle110"}
                data-plasmic-override={overrides.rectangle110}
                className={classNames(projectcss.all, sty.rectangle110)}
              />

              <div
                data-plasmic-name={"rectangle111"}
                data-plasmic-override={overrides.rectangle111}
                className={classNames(projectcss.all, sty.rectangle111)}
              />

              <div
                data-plasmic-name={"rectangle112"}
                data-plasmic-override={overrides.rectangle112}
                className={classNames(projectcss.all, sty.rectangle112)}
              />
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"phGridFourFill32"}
              data-plasmic-override={overrides.phGridFourFill32}
              hasGap={true}
              className={classNames(projectcss.all, sty.phGridFourFill32)}
            >
              <div
                data-plasmic-name={"rectangle113"}
                data-plasmic-override={overrides.rectangle113}
                className={classNames(projectcss.all, sty.rectangle113)}
              />

              <div
                data-plasmic-name={"rectangle114"}
                data-plasmic-override={overrides.rectangle114}
                className={classNames(projectcss.all, sty.rectangle114)}
              />

              <div
                data-plasmic-name={"rectangle115"}
                data-plasmic-override={overrides.rectangle115}
                className={classNames(projectcss.all, sty.rectangle115)}
              />
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"phGridFourFill33"}
              data-plasmic-override={overrides.phGridFourFill33}
              hasGap={true}
              className={classNames(projectcss.all, sty.phGridFourFill33)}
            >
              <div
                data-plasmic-name={"rectangle116"}
                data-plasmic-override={overrides.rectangle116}
                className={classNames(projectcss.all, sty.rectangle116)}
              />

              <div
                data-plasmic-name={"rectangle117"}
                data-plasmic-override={overrides.rectangle117}
                className={classNames(projectcss.all, sty.rectangle117)}
              />

              <div
                data-plasmic-name={"rectangle118"}
                data-plasmic-override={overrides.rectangle118}
                className={classNames(projectcss.all, sty.rectangle118)}
              />
            </Stack__>
          </React.Fragment>
        }
      >
        {"AL"}
      </BtmNavbarTile>
      <BtmNavbarTile
        data-plasmic-name={"btmNavbarTile4"}
        data-plasmic-override={overrides.btmNavbarTile4}
        className={classNames("__wab_instance", sty.btmNavbarTile4)}
        frame1437254298={
          <React.Fragment>
            <Stack__
              as={"div"}
              data-plasmic-name={"phGridFourFill28"}
              data-plasmic-override={overrides.phGridFourFill28}
              hasGap={true}
              className={classNames(projectcss.all, sty.phGridFourFill28)}
            >
              <div
                data-plasmic-name={"rectangle101"}
                data-plasmic-override={overrides.rectangle101}
                className={classNames(projectcss.all, sty.rectangle101)}
              />

              <div
                data-plasmic-name={"rectangle102"}
                data-plasmic-override={overrides.rectangle102}
                className={classNames(projectcss.all, sty.rectangle102)}
              />

              <div
                data-plasmic-name={"rectangle103"}
                data-plasmic-override={overrides.rectangle103}
                className={classNames(projectcss.all, sty.rectangle103)}
              />
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"phGridFourFill29"}
              data-plasmic-override={overrides.phGridFourFill29}
              hasGap={true}
              className={classNames(projectcss.all, sty.phGridFourFill29)}
            >
              <div
                data-plasmic-name={"rectangle104"}
                data-plasmic-override={overrides.rectangle104}
                className={classNames(projectcss.all, sty.rectangle104)}
              />

              <div
                data-plasmic-name={"rectangle105"}
                data-plasmic-override={overrides.rectangle105}
                className={classNames(projectcss.all, sty.rectangle105)}
              />

              <div
                data-plasmic-name={"rectangle106"}
                data-plasmic-override={overrides.rectangle106}
                className={classNames(projectcss.all, sty.rectangle106)}
              />
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"phGridFourFill30"}
              data-plasmic-override={overrides.phGridFourFill30}
              hasGap={true}
              className={classNames(projectcss.all, sty.phGridFourFill30)}
            >
              <div
                data-plasmic-name={"rectangle107"}
                data-plasmic-override={overrides.rectangle107}
                className={classNames(projectcss.all, sty.rectangle107)}
              />

              <div
                data-plasmic-name={"rectangle108"}
                data-plasmic-override={overrides.rectangle108}
                className={classNames(projectcss.all, sty.rectangle108)}
              />

              <div
                data-plasmic-name={"rectangle109"}
                data-plasmic-override={overrides.rectangle109}
                className={classNames(projectcss.all, sty.rectangle109)}
              />
            </Stack__>
          </React.Fragment>
        }
      >
        {"ML"}
      </BtmNavbarTile>
      <BtmNavbarTile
        data-plasmic-name={"btmNavbarTile3"}
        data-plasmic-override={overrides.btmNavbarTile3}
        className={classNames("__wab_instance", sty.btmNavbarTile3)}
        frame1437254298={
          <React.Fragment>
            <Stack__
              as={"div"}
              data-plasmic-name={"phGridFourFill25"}
              data-plasmic-override={overrides.phGridFourFill25}
              hasGap={true}
              className={classNames(projectcss.all, sty.phGridFourFill25)}
            >
              <div
                data-plasmic-name={"rectangle92"}
                data-plasmic-override={overrides.rectangle92}
                className={classNames(projectcss.all, sty.rectangle92)}
              />

              <div
                data-plasmic-name={"rectangle93"}
                data-plasmic-override={overrides.rectangle93}
                className={classNames(projectcss.all, sty.rectangle93)}
              />

              <div
                data-plasmic-name={"rectangle94"}
                data-plasmic-override={overrides.rectangle94}
                className={classNames(projectcss.all, sty.rectangle94)}
              />
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"phGridFourFill26"}
              data-plasmic-override={overrides.phGridFourFill26}
              hasGap={true}
              className={classNames(projectcss.all, sty.phGridFourFill26)}
            >
              <div
                data-plasmic-name={"rectangle95"}
                data-plasmic-override={overrides.rectangle95}
                className={classNames(projectcss.all, sty.rectangle95)}
              />

              <div
                data-plasmic-name={"rectangle96"}
                data-plasmic-override={overrides.rectangle96}
                className={classNames(projectcss.all, sty.rectangle96)}
              />

              <div
                data-plasmic-name={"rectangle97"}
                data-plasmic-override={overrides.rectangle97}
                className={classNames(projectcss.all, sty.rectangle97)}
              />
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"phGridFourFill27"}
              data-plasmic-override={overrides.phGridFourFill27}
              hasGap={true}
              className={classNames(projectcss.all, sty.phGridFourFill27)}
            >
              <div
                data-plasmic-name={"rectangle98"}
                data-plasmic-override={overrides.rectangle98}
                className={classNames(projectcss.all, sty.rectangle98)}
              />

              <div
                data-plasmic-name={"rectangle99"}
                data-plasmic-override={overrides.rectangle99}
                className={classNames(projectcss.all, sty.rectangle99)}
              />

              <div
                data-plasmic-name={"rectangle100"}
                data-plasmic-override={overrides.rectangle100}
                className={classNames(projectcss.all, sty.rectangle100)}
              />
            </Stack__>
          </React.Fragment>
        }
      >
        {"PL"}
      </BtmNavbarTile>
      <BtmNavbarTile
        data-plasmic-name={"btmNavbarTile2"}
        data-plasmic-override={overrides.btmNavbarTile2}
        className={classNames("__wab_instance", sty.btmNavbarTile2)}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  frame1437254343: [
    "frame1437254343",
    "btmNavbarTile",
    "phGridFourFill19",
    "rectangle74",
    "rectangle75",
    "rectangle76",
    "phGridFourFill20",
    "rectangle77",
    "rectangle78",
    "rectangle79",
    "phGridFourFill21",
    "rectangle80",
    "rectangle81",
    "rectangle82",
    "btmNavbarTile7",
    "phGridFourFill37",
    "rectangle128",
    "rectangle129",
    "rectangle130",
    "phGridFourFill38",
    "rectangle131",
    "rectangle132",
    "rectangle133",
    "phGridFourFill39",
    "rectangle134",
    "rectangle135",
    "rectangle136",
    "btmNavbarTile6",
    "phGridFourFill34",
    "rectangle119",
    "rectangle120",
    "rectangle121",
    "phGridFourFill35",
    "rectangle122",
    "rectangle123",
    "rectangle124",
    "phGridFourFill36",
    "rectangle125",
    "rectangle126",
    "rectangle127",
    "btmNavbarTile5",
    "phGridFourFill31",
    "rectangle110",
    "rectangle111",
    "rectangle112",
    "phGridFourFill32",
    "rectangle113",
    "rectangle114",
    "rectangle115",
    "phGridFourFill33",
    "rectangle116",
    "rectangle117",
    "rectangle118",
    "btmNavbarTile4",
    "phGridFourFill28",
    "rectangle101",
    "rectangle102",
    "rectangle103",
    "phGridFourFill29",
    "rectangle104",
    "rectangle105",
    "rectangle106",
    "phGridFourFill30",
    "rectangle107",
    "rectangle108",
    "rectangle109",
    "btmNavbarTile3",
    "phGridFourFill25",
    "rectangle92",
    "rectangle93",
    "rectangle94",
    "phGridFourFill26",
    "rectangle95",
    "rectangle96",
    "rectangle97",
    "phGridFourFill27",
    "rectangle98",
    "rectangle99",
    "rectangle100",
    "btmNavbarTile2"
  ],
  btmNavbarTile: [
    "btmNavbarTile",
    "phGridFourFill19",
    "rectangle74",
    "rectangle75",
    "rectangle76",
    "phGridFourFill20",
    "rectangle77",
    "rectangle78",
    "rectangle79",
    "phGridFourFill21",
    "rectangle80",
    "rectangle81",
    "rectangle82"
  ],
  phGridFourFill19: [
    "phGridFourFill19",
    "rectangle74",
    "rectangle75",
    "rectangle76"
  ],
  rectangle74: ["rectangle74"],
  rectangle75: ["rectangle75"],
  rectangle76: ["rectangle76"],
  phGridFourFill20: [
    "phGridFourFill20",
    "rectangle77",
    "rectangle78",
    "rectangle79"
  ],
  rectangle77: ["rectangle77"],
  rectangle78: ["rectangle78"],
  rectangle79: ["rectangle79"],
  phGridFourFill21: [
    "phGridFourFill21",
    "rectangle80",
    "rectangle81",
    "rectangle82"
  ],
  rectangle80: ["rectangle80"],
  rectangle81: ["rectangle81"],
  rectangle82: ["rectangle82"],
  btmNavbarTile7: [
    "btmNavbarTile7",
    "phGridFourFill37",
    "rectangle128",
    "rectangle129",
    "rectangle130",
    "phGridFourFill38",
    "rectangle131",
    "rectangle132",
    "rectangle133",
    "phGridFourFill39",
    "rectangle134",
    "rectangle135",
    "rectangle136"
  ],
  phGridFourFill37: [
    "phGridFourFill37",
    "rectangle128",
    "rectangle129",
    "rectangle130"
  ],
  rectangle128: ["rectangle128"],
  rectangle129: ["rectangle129"],
  rectangle130: ["rectangle130"],
  phGridFourFill38: [
    "phGridFourFill38",
    "rectangle131",
    "rectangle132",
    "rectangle133"
  ],
  rectangle131: ["rectangle131"],
  rectangle132: ["rectangle132"],
  rectangle133: ["rectangle133"],
  phGridFourFill39: [
    "phGridFourFill39",
    "rectangle134",
    "rectangle135",
    "rectangle136"
  ],
  rectangle134: ["rectangle134"],
  rectangle135: ["rectangle135"],
  rectangle136: ["rectangle136"],
  btmNavbarTile6: [
    "btmNavbarTile6",
    "phGridFourFill34",
    "rectangle119",
    "rectangle120",
    "rectangle121",
    "phGridFourFill35",
    "rectangle122",
    "rectangle123",
    "rectangle124",
    "phGridFourFill36",
    "rectangle125",
    "rectangle126",
    "rectangle127"
  ],
  phGridFourFill34: [
    "phGridFourFill34",
    "rectangle119",
    "rectangle120",
    "rectangle121"
  ],
  rectangle119: ["rectangle119"],
  rectangle120: ["rectangle120"],
  rectangle121: ["rectangle121"],
  phGridFourFill35: [
    "phGridFourFill35",
    "rectangle122",
    "rectangle123",
    "rectangle124"
  ],
  rectangle122: ["rectangle122"],
  rectangle123: ["rectangle123"],
  rectangle124: ["rectangle124"],
  phGridFourFill36: [
    "phGridFourFill36",
    "rectangle125",
    "rectangle126",
    "rectangle127"
  ],
  rectangle125: ["rectangle125"],
  rectangle126: ["rectangle126"],
  rectangle127: ["rectangle127"],
  btmNavbarTile5: [
    "btmNavbarTile5",
    "phGridFourFill31",
    "rectangle110",
    "rectangle111",
    "rectangle112",
    "phGridFourFill32",
    "rectangle113",
    "rectangle114",
    "rectangle115",
    "phGridFourFill33",
    "rectangle116",
    "rectangle117",
    "rectangle118"
  ],
  phGridFourFill31: [
    "phGridFourFill31",
    "rectangle110",
    "rectangle111",
    "rectangle112"
  ],
  rectangle110: ["rectangle110"],
  rectangle111: ["rectangle111"],
  rectangle112: ["rectangle112"],
  phGridFourFill32: [
    "phGridFourFill32",
    "rectangle113",
    "rectangle114",
    "rectangle115"
  ],
  rectangle113: ["rectangle113"],
  rectangle114: ["rectangle114"],
  rectangle115: ["rectangle115"],
  phGridFourFill33: [
    "phGridFourFill33",
    "rectangle116",
    "rectangle117",
    "rectangle118"
  ],
  rectangle116: ["rectangle116"],
  rectangle117: ["rectangle117"],
  rectangle118: ["rectangle118"],
  btmNavbarTile4: [
    "btmNavbarTile4",
    "phGridFourFill28",
    "rectangle101",
    "rectangle102",
    "rectangle103",
    "phGridFourFill29",
    "rectangle104",
    "rectangle105",
    "rectangle106",
    "phGridFourFill30",
    "rectangle107",
    "rectangle108",
    "rectangle109"
  ],
  phGridFourFill28: [
    "phGridFourFill28",
    "rectangle101",
    "rectangle102",
    "rectangle103"
  ],
  rectangle101: ["rectangle101"],
  rectangle102: ["rectangle102"],
  rectangle103: ["rectangle103"],
  phGridFourFill29: [
    "phGridFourFill29",
    "rectangle104",
    "rectangle105",
    "rectangle106"
  ],
  rectangle104: ["rectangle104"],
  rectangle105: ["rectangle105"],
  rectangle106: ["rectangle106"],
  phGridFourFill30: [
    "phGridFourFill30",
    "rectangle107",
    "rectangle108",
    "rectangle109"
  ],
  rectangle107: ["rectangle107"],
  rectangle108: ["rectangle108"],
  rectangle109: ["rectangle109"],
  btmNavbarTile3: [
    "btmNavbarTile3",
    "phGridFourFill25",
    "rectangle92",
    "rectangle93",
    "rectangle94",
    "phGridFourFill26",
    "rectangle95",
    "rectangle96",
    "rectangle97",
    "phGridFourFill27",
    "rectangle98",
    "rectangle99",
    "rectangle100"
  ],
  phGridFourFill25: [
    "phGridFourFill25",
    "rectangle92",
    "rectangle93",
    "rectangle94"
  ],
  rectangle92: ["rectangle92"],
  rectangle93: ["rectangle93"],
  rectangle94: ["rectangle94"],
  phGridFourFill26: [
    "phGridFourFill26",
    "rectangle95",
    "rectangle96",
    "rectangle97"
  ],
  rectangle95: ["rectangle95"],
  rectangle96: ["rectangle96"],
  rectangle97: ["rectangle97"],
  phGridFourFill27: [
    "phGridFourFill27",
    "rectangle98",
    "rectangle99",
    "rectangle100"
  ],
  rectangle98: ["rectangle98"],
  rectangle99: ["rectangle99"],
  rectangle100: ["rectangle100"],
  btmNavbarTile2: ["btmNavbarTile2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  frame1437254343: "div";
  btmNavbarTile: typeof BtmNavbarTile;
  phGridFourFill19: "div";
  rectangle74: "div";
  rectangle75: "div";
  rectangle76: "div";
  phGridFourFill20: "div";
  rectangle77: "div";
  rectangle78: "div";
  rectangle79: "div";
  phGridFourFill21: "div";
  rectangle80: "div";
  rectangle81: "div";
  rectangle82: "div";
  btmNavbarTile7: typeof BtmNavbarTile;
  phGridFourFill37: "div";
  rectangle128: "div";
  rectangle129: "div";
  rectangle130: "div";
  phGridFourFill38: "div";
  rectangle131: "div";
  rectangle132: "div";
  rectangle133: "div";
  phGridFourFill39: "div";
  rectangle134: "div";
  rectangle135: "div";
  rectangle136: "div";
  btmNavbarTile6: typeof BtmNavbarTile;
  phGridFourFill34: "div";
  rectangle119: "div";
  rectangle120: "div";
  rectangle121: "div";
  phGridFourFill35: "div";
  rectangle122: "div";
  rectangle123: "div";
  rectangle124: "div";
  phGridFourFill36: "div";
  rectangle125: "div";
  rectangle126: "div";
  rectangle127: "div";
  btmNavbarTile5: typeof BtmNavbarTile;
  phGridFourFill31: "div";
  rectangle110: "div";
  rectangle111: "div";
  rectangle112: "div";
  phGridFourFill32: "div";
  rectangle113: "div";
  rectangle114: "div";
  rectangle115: "div";
  phGridFourFill33: "div";
  rectangle116: "div";
  rectangle117: "div";
  rectangle118: "div";
  btmNavbarTile4: typeof BtmNavbarTile;
  phGridFourFill28: "div";
  rectangle101: "div";
  rectangle102: "div";
  rectangle103: "div";
  phGridFourFill29: "div";
  rectangle104: "div";
  rectangle105: "div";
  rectangle106: "div";
  phGridFourFill30: "div";
  rectangle107: "div";
  rectangle108: "div";
  rectangle109: "div";
  btmNavbarTile3: typeof BtmNavbarTile;
  phGridFourFill25: "div";
  rectangle92: "div";
  rectangle93: "div";
  rectangle94: "div";
  phGridFourFill26: "div";
  rectangle95: "div";
  rectangle96: "div";
  rectangle97: "div";
  phGridFourFill27: "div";
  rectangle98: "div";
  rectangle99: "div";
  rectangle100: "div";
  btmNavbarTile2: typeof BtmNavbarTile;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBtmNavbar__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBtmNavbar__VariantsArgs;
    args?: PlasmicBtmNavbar__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicBtmNavbar__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicBtmNavbar__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicBtmNavbar__ArgProps,
          internalVariantPropNames: PlasmicBtmNavbar__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicBtmNavbar__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "frame1437254343") {
    func.displayName = "PlasmicBtmNavbar";
  } else {
    func.displayName = `PlasmicBtmNavbar.${nodeName}`;
  }
  return func;
}

export const PlasmicBtmNavbar = Object.assign(
  // Top-level PlasmicBtmNavbar renders the root element
  makeNodeComponent("frame1437254343"),
  {
    // Helper components rendering sub-elements
    btmNavbarTile: makeNodeComponent("btmNavbarTile"),
    phGridFourFill19: makeNodeComponent("phGridFourFill19"),
    rectangle74: makeNodeComponent("rectangle74"),
    rectangle75: makeNodeComponent("rectangle75"),
    rectangle76: makeNodeComponent("rectangle76"),
    phGridFourFill20: makeNodeComponent("phGridFourFill20"),
    rectangle77: makeNodeComponent("rectangle77"),
    rectangle78: makeNodeComponent("rectangle78"),
    rectangle79: makeNodeComponent("rectangle79"),
    phGridFourFill21: makeNodeComponent("phGridFourFill21"),
    rectangle80: makeNodeComponent("rectangle80"),
    rectangle81: makeNodeComponent("rectangle81"),
    rectangle82: makeNodeComponent("rectangle82"),
    btmNavbarTile7: makeNodeComponent("btmNavbarTile7"),
    phGridFourFill37: makeNodeComponent("phGridFourFill37"),
    rectangle128: makeNodeComponent("rectangle128"),
    rectangle129: makeNodeComponent("rectangle129"),
    rectangle130: makeNodeComponent("rectangle130"),
    phGridFourFill38: makeNodeComponent("phGridFourFill38"),
    rectangle131: makeNodeComponent("rectangle131"),
    rectangle132: makeNodeComponent("rectangle132"),
    rectangle133: makeNodeComponent("rectangle133"),
    phGridFourFill39: makeNodeComponent("phGridFourFill39"),
    rectangle134: makeNodeComponent("rectangle134"),
    rectangle135: makeNodeComponent("rectangle135"),
    rectangle136: makeNodeComponent("rectangle136"),
    btmNavbarTile6: makeNodeComponent("btmNavbarTile6"),
    phGridFourFill34: makeNodeComponent("phGridFourFill34"),
    rectangle119: makeNodeComponent("rectangle119"),
    rectangle120: makeNodeComponent("rectangle120"),
    rectangle121: makeNodeComponent("rectangle121"),
    phGridFourFill35: makeNodeComponent("phGridFourFill35"),
    rectangle122: makeNodeComponent("rectangle122"),
    rectangle123: makeNodeComponent("rectangle123"),
    rectangle124: makeNodeComponent("rectangle124"),
    phGridFourFill36: makeNodeComponent("phGridFourFill36"),
    rectangle125: makeNodeComponent("rectangle125"),
    rectangle126: makeNodeComponent("rectangle126"),
    rectangle127: makeNodeComponent("rectangle127"),
    btmNavbarTile5: makeNodeComponent("btmNavbarTile5"),
    phGridFourFill31: makeNodeComponent("phGridFourFill31"),
    rectangle110: makeNodeComponent("rectangle110"),
    rectangle111: makeNodeComponent("rectangle111"),
    rectangle112: makeNodeComponent("rectangle112"),
    phGridFourFill32: makeNodeComponent("phGridFourFill32"),
    rectangle113: makeNodeComponent("rectangle113"),
    rectangle114: makeNodeComponent("rectangle114"),
    rectangle115: makeNodeComponent("rectangle115"),
    phGridFourFill33: makeNodeComponent("phGridFourFill33"),
    rectangle116: makeNodeComponent("rectangle116"),
    rectangle117: makeNodeComponent("rectangle117"),
    rectangle118: makeNodeComponent("rectangle118"),
    btmNavbarTile4: makeNodeComponent("btmNavbarTile4"),
    phGridFourFill28: makeNodeComponent("phGridFourFill28"),
    rectangle101: makeNodeComponent("rectangle101"),
    rectangle102: makeNodeComponent("rectangle102"),
    rectangle103: makeNodeComponent("rectangle103"),
    phGridFourFill29: makeNodeComponent("phGridFourFill29"),
    rectangle104: makeNodeComponent("rectangle104"),
    rectangle105: makeNodeComponent("rectangle105"),
    rectangle106: makeNodeComponent("rectangle106"),
    phGridFourFill30: makeNodeComponent("phGridFourFill30"),
    rectangle107: makeNodeComponent("rectangle107"),
    rectangle108: makeNodeComponent("rectangle108"),
    rectangle109: makeNodeComponent("rectangle109"),
    btmNavbarTile3: makeNodeComponent("btmNavbarTile3"),
    phGridFourFill25: makeNodeComponent("phGridFourFill25"),
    rectangle92: makeNodeComponent("rectangle92"),
    rectangle93: makeNodeComponent("rectangle93"),
    rectangle94: makeNodeComponent("rectangle94"),
    phGridFourFill26: makeNodeComponent("phGridFourFill26"),
    rectangle95: makeNodeComponent("rectangle95"),
    rectangle96: makeNodeComponent("rectangle96"),
    rectangle97: makeNodeComponent("rectangle97"),
    phGridFourFill27: makeNodeComponent("phGridFourFill27"),
    rectangle98: makeNodeComponent("rectangle98"),
    rectangle99: makeNodeComponent("rectangle99"),
    rectangle100: makeNodeComponent("rectangle100"),
    btmNavbarTile2: makeNodeComponent("btmNavbarTile2"),

    // Metadata about props expected for PlasmicBtmNavbar
    internalVariantProps: PlasmicBtmNavbar__VariantProps,
    internalArgProps: PlasmicBtmNavbar__ArgProps
  }
);

export default PlasmicBtmNavbar;
/* prettier-ignore-end */
