/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jND4haQkMjdpXVH9tN144R
// Component: NMuDVhuXDIhc

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { BasePopover } from "@plasmicpkgs/react-aria/skinny/registerPopover";
import { BaseListBox } from "@plasmicpkgs/react-aria/skinny/registerListBox";
import { listboxHelpers as BaseListBox_Helpers } from "@plasmicpkgs/react-aria/skinny/registerListBox";
import MenuItem2 from "../../MenuItem2"; // plasmic-import: yWcgJkcChm8E/component
import MenuSection2 from "../../MenuSection2"; // plasmic-import: UVY77y08KHgv/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: jND4haQkMjdpXVH9tN144R/projectcss
import sty from "./PlasmicMenuPopover2.module.css"; // plasmic-import: NMuDVhuXDIhc/css

createPlasmicElementProxy;

export type PlasmicMenuPopover2__VariantMembers = {};
export type PlasmicMenuPopover2__VariantsArgs = {};
type VariantPropType = keyof PlasmicMenuPopover2__VariantsArgs;
export const PlasmicMenuPopover2__VariantProps = new Array<VariantPropType>();

export type PlasmicMenuPopover2__ArgsType = {
  offset?: number;
  menuItems?: React.ReactNode;
  initialSelectedKey?: "Dynamic options";
};
type ArgPropType = keyof PlasmicMenuPopover2__ArgsType;
export const PlasmicMenuPopover2__ArgProps = new Array<ArgPropType>(
  "offset",
  "menuItems",
  "initialSelectedKey"
);

export type PlasmicMenuPopover2__OverridesType = {
  root?: Flex__<typeof BasePopover>;
  ariaListBox?: Flex__<typeof BaseListBox>;
};

export interface DefaultMenuPopover2Props {
  offset?: number;
  menuItems?: React.ReactNode;
  initialSelectedKey?: "Dynamic options";
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicMenuPopover2__RenderFunc(props: {
  variants: PlasmicMenuPopover2__VariantsArgs;
  args: PlasmicMenuPopover2__ArgsType;
  overrides: PlasmicMenuPopover2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          offset: 2
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "ariaListBox.selectedValue",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          $props["initialSelectedKey"],

        onMutate: generateOnMutateForSpec("selectedValue", BaseListBox_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <BasePopover
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "__wab_instance",
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root
      )}
      matchTriggerWidth={true}
      offset={args.offset}
      placement={"bottom"}
      resetClassName={classNames(
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens
      )}
      shouldFlip={true}
    >
      {(() => {
        const child$Props = {
          className: classNames("__wab_instance", sty.ariaListBox),
          defaultSelectedKeys: args.initialSelectedKey,
          onSelectionChange: async (...eventArgs: any) => {
            generateStateOnChangePropForCodeComponents(
              $state,
              "selectedValue",
              ["ariaListBox", "selectedValue"],
              BaseListBox_Helpers
            ).apply(null, eventArgs);
          },
          selectedKeys: generateStateValueProp($state, [
            "ariaListBox",
            "selectedValue"
          ]),
          selectionMode: "single"
        };
        initializeCodeComponentStates(
          $state,
          [
            {
              name: "selectedValue",
              plasmicStateName: "ariaListBox.selectedValue"
            }
          ],
          [],
          BaseListBox_Helpers ?? {},
          child$Props
        );

        return (
          <BaseListBox
            data-plasmic-name={"ariaListBox"}
            data-plasmic-override={overrides.ariaListBox}
            {...child$Props}
          >
            {renderPlasmicSlot({
              defaultContents: (
                <React.Fragment>
                  <MenuItem2
                    className={classNames(
                      "__wab_instance",
                      sty.menuItem2__zsxZg
                    )}
                    value={"item1"}
                  />

                  <MenuItem2
                    className={classNames(
                      "__wab_instance",
                      sty.menuItem2__dsMqB
                    )}
                    label={"Item 2"}
                    value={"item2"}
                  />

                  <MenuItem2
                    className={classNames(
                      "__wab_instance",
                      sty.menuItem2__yibqD
                    )}
                    label={"Item 3"}
                    value={"item3"}
                  />

                  <MenuSection2
                    className={classNames(
                      "__wab_instance",
                      sty.menuSection2___2BRu
                    )}
                    items={
                      <React.Fragment>
                        <MenuItem2
                          label={"Section Item 1"}
                          value={"section-item-1"}
                        />

                        <MenuItem2
                          label={"Section Item 2"}
                          value={"section-item-2"}
                        />

                        <MenuItem2
                          label={"Section Item 3"}
                          value={"section-item-3"}
                        />
                      </React.Fragment>
                    }
                  />
                </React.Fragment>
              ),
              value: args.menuItems
            })}
          </BaseListBox>
        );
      })()}
    </BasePopover>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "ariaListBox"],
  ariaListBox: ["ariaListBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: typeof BasePopover;
  ariaListBox: typeof BaseListBox;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMenuPopover2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMenuPopover2__VariantsArgs;
    args?: PlasmicMenuPopover2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicMenuPopover2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicMenuPopover2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicMenuPopover2__ArgProps,
          internalVariantPropNames: PlasmicMenuPopover2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMenuPopover2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMenuPopover2";
  } else {
    func.displayName = `PlasmicMenuPopover2.${nodeName}`;
  }
  return func;
}

export const PlasmicMenuPopover2 = Object.assign(
  // Top-level PlasmicMenuPopover2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    ariaListBox: makeNodeComponent("ariaListBox"),

    // Metadata about props expected for PlasmicMenuPopover2
    internalVariantProps: PlasmicMenuPopover2__VariantProps,
    internalArgProps: PlasmicMenuPopover2__ArgProps
  }
);

export default PlasmicMenuPopover2;
/* prettier-ignore-end */
