/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: i2rVY7FDpNEigoftN9kimn

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsznUlWztU2MQp } from "./PlasmicGlobalVariant__Screen";
import { LocaleValue, useLocale } from "./PlasmicGlobalVariant__Locale";

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsznUlWztU2MQp,
  locale: useLocale
});
