/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sYXMYndb1v9rTXALzdZyn1
// Component: QYMLkOaLyjNU

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { BaseSection } from "@plasmicpkgs/react-aria/skinny/registerSection";
import MenuItem2 from "../../MenuItem2"; // plasmic-import: UZ680D6oFu4N/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: sYXMYndb1v9rTXALzdZyn1/projectcss
import sty from "./PlasmicMenuSection2.module.css"; // plasmic-import: QYMLkOaLyjNU/css

createPlasmicElementProxy;

export type PlasmicMenuSection2__VariantMembers = {};
export type PlasmicMenuSection2__VariantsArgs = {};
type VariantPropType = keyof PlasmicMenuSection2__VariantsArgs;
export const PlasmicMenuSection2__VariantProps = new Array<VariantPropType>();

export type PlasmicMenuSection2__ArgsType = {
  header?: React.ReactNode;
  items?: React.ReactNode;
};
type ArgPropType = keyof PlasmicMenuSection2__ArgsType;
export const PlasmicMenuSection2__ArgProps = new Array<ArgPropType>(
  "header",
  "items"
);

export type PlasmicMenuSection2__OverridesType = {
  root?: Flex__<typeof BaseSection>;
  freeBox?: Flex__<"div">;
};

export interface DefaultMenuSection2Props {
  header?: React.ReactNode;
  items?: React.ReactNode;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicMenuSection2__RenderFunc(props: {
  variants: PlasmicMenuSection2__VariantsArgs;
  args: PlasmicMenuSection2__ArgsType;
  overrides: PlasmicMenuSection2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <BaseSection
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "__wab_instance",
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root
      )}
      header={
        <div
          data-plasmic-name={"freeBox"}
          data-plasmic-override={overrides.freeBox}
          className={classNames(projectcss.all, sty.freeBox)}
        >
          {renderPlasmicSlot({
            defaultContents: "Section Header",
            value: args.header,
            className: classNames(sty.slotTargetHeader)
          })}
        </div>
      }
      items={renderPlasmicSlot({
        defaultContents: (
          <React.Fragment>
            <MenuItem2 label={"Section Item 1"} value={"section-item-1"} />

            <MenuItem2 label={"Section Item 2"} value={"section-item-2"} />

            <MenuItem2 label={"Section Item 3"} value={"section-item-3"} />
          </React.Fragment>
        ),
        value: args.items
      })}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: typeof BaseSection;
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMenuSection2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMenuSection2__VariantsArgs;
    args?: PlasmicMenuSection2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicMenuSection2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicMenuSection2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicMenuSection2__ArgProps,
          internalVariantPropNames: PlasmicMenuSection2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMenuSection2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMenuSection2";
  } else {
    func.displayName = `PlasmicMenuSection2.${nodeName}`;
  }
  return func;
}

export const PlasmicMenuSection2 = Object.assign(
  // Top-level PlasmicMenuSection2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicMenuSection2
    internalVariantProps: PlasmicMenuSection2__VariantProps,
    internalArgProps: PlasmicMenuSection2__ArgProps
  }
);

export default PlasmicMenuSection2;
/* prettier-ignore-end */
