CREATE TABLE lesion (
    id INTEGER,
    name_fr TEXT,
    name_en TEXT,
    category_fr TEXT,
    category_en TEXT,
    image_fr TEXT,
    video_fr TEXT,
    macro_category_fr TEXT,
    multi_step BOOLEAN,
    next_step TEXT,
    previous_step TEXT,
    image_en TEXT,
    video_en TEXT,
    image_trauma TEXT,
    face TEXT,
    has_options BOOLEAN
);

INSERT INTO lesion (id, name_fr, name_en, category_fr, category_en, image_fr, video_fr, macro_category_fr, multi_step, next_step, previous_step, image_en, video_en, image_trauma, face, has_options) VALUES
(60, 'Vagin / Cloison Rectovaginale', 'Vagina / Rectovaginal Space', 'Médiocentral', 'Mediocentral', 'image_fr/VaginaRVS_FR.jpg', 'video_fr/vagin.mp4', 'Profonde', FALSE, NULL, NULL, 'image_en/VaginaRVS_EN.jpg', NULL, 'Cloison_rectovaginale.png', NULL, FALSE),
(2, 'Implant Péritonéal Unique', 'Single Peritoneal Implant', 'Superficielle', 'Superficial', NULL, NULL, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, FALSE),
(3, 'Implants Péritonéaux Multiples', 'Multiple Peritoneal Implants', 'Superficielle', 'Superficial', NULL, NULL, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, FALSE),
(11, 'Hématosalpinx Endométriosique', 'Endometriotic Hematosalpinx', 'Annexielle > côté gauche', 'Adnexal > left side', NULL, NULL, NULL, TRUE, NULL, 'Annexielle > côté droit', NULL, NULL, 'hematosalpinx.png', 'gauche', FALSE),
(9, 'Microendométriome', 'Microendometrioma', 'Annexielle > côté gauche', 'Adnexal > left side', NULL, NULL, NULL, TRUE, NULL, 'Annexielle > côté droit', NULL, NULL, 'microendometriome.png', 'gauche', FALSE),
(7, 'Kissing Ovaries', 'Kissing Ovaries', 'Superficielle', 'Superficial', NULL, NULL, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, FALSE),
(17, 'Hématosalpinx Endométriosique', 'Endometriotic Hematosalpinx', 'Annexielle > côté droit', 'Adnexal > right side', NULL, NULL, NULL, TRUE, 'Annexielle > côté gauche', NULL, NULL, NULL, 'hematosalpinx.png', 'droite', FALSE),
(12, 'Fossette Ovarienne', 'Ovarian Fossa', 'Annexielle > côté gauche', 'Adnexal > left side', NULL, NULL, NULL, TRUE, NULL, 'Annexielle > côté droit', NULL, NULL, 'fossette_ovarienne.png', 'gauche', FALSE),
(13, 'Hydrosalpinx Associé', 'Associated Hydrosalpinx', 'Annexielle > côté gauche', 'Adnexal > left side', NULL, NULL, NULL, TRUE, NULL, 'Annexielle > côté droit', NULL, NULL, 'hydrosalpinx_associe.png', 'gauche', FALSE),
(4, 'Adhérence(s)', 'Adhesion', 'Superficielle', 'Superficial', NULL, NULL, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, FALSE),
(21, 'Ligament Rond Distal', 'Distal Round Ligament', 'Antérolatéral droit', 'Right anterolateral', 'image_fr/Ligament_rond_D.jpg', 'video_fr/rond_distal.mp4', 'Profonde', TRUE, 'Antérolatéral gauche', NULL, 'image_en/Ligament_rond_D.jpg', NULL, 'Ligament_rond_distal.png', 'droite', FALSE),
(22, 'Espace périvésical', 'Perivesical Space', 'Antérolatéral droit', 'Right anterolateral', 'image_fr/Espace_perivesical_D.jpg', 'video_fr/perivesical.mp4', 'Profonde', TRUE, 'Antérolatéral gauche', NULL, 'image_en/Espace_perivesical_D.jpg', NULL, 'Espace_perivesical.png', 'droite', FALSE),
(18, 'Fossette Ovarienne', 'Ovarian Fossa', 'Annexielle > côté droit', 'Adnexal > right side', NULL, NULL, NULL, TRUE, 'Annexielle > côté gauche', NULL, NULL, NULL, 'fossette_ovarienne.png', 'droite', FALSE),
(19, 'Hydrosalpinx Associé', 'Associated Hydrosalpinx', 'Annexielle > côté droit', 'Adnexal > right side', NULL, NULL, NULL, TRUE, 'Annexielle > côté gauche', NULL, NULL, NULL, 'hydrosalpinx_associe.png', 'droite', FALSE),
(15, 'Microendométriome', 'Microendometrioma', 'Annexielle > côté droit', 'Adnexal > right side', NULL, NULL, NULL, TRUE, 'Annexielle > côté gauche', NULL, NULL, NULL, 'microendometriome.png', 'droite', FALSE),
(52, NULL, NULL, 'Profonde', 'Deep', NULL, NULL, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, FALSE),
(16, 'Endométriome (>1 cm)', 'Endometrioma (>1 cm)', 'Annexielle > côté droit', 'Adnexal > right side', NULL, NULL, NULL, TRUE, 'Annexielle > côté gauche', NULL, NULL, NULL, NULL, 'droite', TRUE),
(10, 'Endométriome (>1 cm)', 'Endometrioma (>1 cm)', 'Annexielle > côté gauche', 'Adnexal > left side', NULL, NULL, NULL, TRUE, NULL, 'Annexielle > côté droit', NULL, NULL, NULL, 'gauche', TRUE),
(57, 'Faux Kyste Péritonéal', 'Pseudocyst Peritoneal', 'Superficielle', 'Superficial', NULL, NULL, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, FALSE),
(61, 'Myomètre Externe', 'Outer Myometrium', 'Médiocentral', 'Mediocentral', 'image_fr/rup_ea.jpg', 'video_fr/myom_externe.mp4', 'Profonde', FALSE, NULL, NULL, 'image_en/rup_ea.jpg', NULL, NULL, NULL, FALSE),
(32, 'Paroi Pelvienne ML (+/- Nerf Obturateur)', 'Pelvic Wall (including +/- Obturator Nerve)', 'Médiolatéral gauche', 'Left mediolateral', 'image_fr/Obturateur_G.jpg', 'video_fr/paroi_pelvienne_ML.mp4', 'Profonde', TRUE, NULL, 'Médiolatéral droit', 'image_en/Obturateur_G.jpg', NULL, 'Obturateur.png', 'gauche', FALSE),
(30, 'Paramètre Médiolatéral', 'Mediolateral Parametrium', 'Médiolatéral gauche', 'Left mediolateral', 'image_fr/Parametre_mediolateral_G.jpg', 'video_fr/parametre_ML.mp4', 'Profonde', TRUE, NULL, 'Médiolatéral droit', 'image_en/Parametre_mediolateral_G.jpg', NULL, 'Parametre_mediolateral.png', 'gauche', FALSE),
(29, 'Paroi Pelvienne ML (+/- Nerf Obturateur)', 'Pelvic Wall (including +/- Obturator Nerve)', 'Médiolatéral droit', 'Right mediolateral', 'image_fr/Obturateur_D.jpg', 'video_fr/paroi_pelvienne_ML.mp4', 'Profonde', TRUE, 'Médiolatéral gauche', NULL, 'image_en/Obturateur_D.jpg', NULL, 'Obturateur.png', 'droite', FALSE),
(53, 'Adénomyose Interne', 'Internal Adenomyosis', 'Pathologies associées', 'Associated pathologies', NULL, NULL, 'Profonde', NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE),
(36, 'Paroi Pelvienne PL (+/- Nerf Sciatique)', 'Pelvic Wall (including +/- Sciatic Nerve)', 'Postérolatéral droit', 'Right posterolateral', 'image_fr/Sciatique_D.jpg', 'video_fr/Paroi_pelvienne_PL.mp4', 'Profonde', TRUE, 'Postérolatéral gauche', NULL, 'image_en/Sciatique_D.jpg', NULL, 'Sciatique.png', 'droite', FALSE),
(39, 'Paroi Pelvienne PL (S3, S4)', 'Pelvic Wall (S3, S4 levels)', 'Postérolatéral gauche', 'Left posterolateral', 'image_fr/Pelvic_wall_S3_S4_levels_DG.jpg', 'video_fr/Paroi_pelvienne_PL.mp4', 'Profonde', TRUE, NULL, 'Postérolatéral droit', 'image_en/Pelvic_wall_S3_S4_levels_DG.jpg', NULL, 'Paroi_pelvienne_S3_S4.png', 'gauche', FALSE),
(34, 'Lame Sacro-Rectale', 'Sacro-Rectal Ligament', 'Postérolatéral droit', 'Right posterolateral', 'image_fr/Lame_D.jpg', 'video_fr/parametre_PL.mp4', 'Profonde', TRUE, 'Postérolatéral gauche', NULL, 'image_en/Lame_D.jpg', NULL, 'Lame.png', 'droite', FALSE),
(27, 'Paramètre Médiolatéral', 'Mediolateral Parametrium', 'Médiolatéral droit', 'Right mediolateral', 'image_fr/Parametre_mediolateral_D.jpg', 'video_fr/parametre_ML.mp4', 'Profonde', TRUE, 'Médiolatéral gauche', NULL, 'image_en/Parametre_mediolateral_D.jpg', NULL, 'Parametre_mediolateral.png', 'droite', FALSE),
(26, 'Nerf Fémoral', 'Femoral Nerve', 'Antérolatéral gauche', 'Left anterolateral', 'image_fr/Nerf_femoral_G.jpg', NULL, 'Profonde', TRUE, NULL, 'Antérolatéral droit', 'image_en/Nerf_femoral_G.jpg', NULL, 'Nerf_femoral.png', 'gauche', FALSE),
(35, 'Paroi Pelvienne PL (S3, S4)', 'Pelvic Wall (S3, S4 levels)', 'Postérolatéral droit', 'Right posterolateral', 'image_fr/Pelvic_wall_S3_S4_levels_DG.jpg', 'video_fr/Paroi_pelvienne_PL.mp4', 'Profonde', TRUE, 'Postérolatéral gauche', NULL, 'image_en/Pelvic_wall_S3_S4_levels_DG.jpg', NULL, 'Paroi_pelvienne_S3_S4.png', 'droite', FALSE),
(23, 'Nerf Fémoral', 'Femoral Nerve', 'Antérolatéral droit', 'Right anterolateral', 'image_fr/Nerf_femoral_D.jpg', NULL, 'Profonde', TRUE, 'Antérolatéral gauche', NULL, 'image_en/Nerf_femoral_D.jpg', NULL, 'Nerf_femoral.png', 'droite', FALSE),
(31, 'Uretère', 'Ureter', 'Médiolatéral gauche', 'Left mediolateral', 'image_fr/Uretere_DG.jpg', 'video_fr/uretere.mp4', 'Profonde', TRUE, NULL, 'Médiolatéral droit', 'image_en/Uretere_DG.jpg', NULL, 'Ureter.png', 'gauche', FALSE),
(58, 'Peritoneal Pocket', 'Peritoneal Pocket', 'Superficielle', 'Superficial', NULL, NULL, NULL, FALSE, NULL, NULL, NULL, NULL, NULL, NULL, FALSE),
(40, 'Paroi Pelvienne PL (+/- Nerf Sciatique)', 'Pelvic Wall (including +/- Sciatic Nerve)', 'Postérolatéral gauche', 'Left posterolateral', 'image_fr/Sciatique_G.jpg', 'video_fr/Paroi_pelvienne_PL.mp4', 'Profonde', TRUE, NULL, 'Postérolatéral droit', 'image_en/Sciatique_G.jpg', NULL, 'Sciatique.png', 'gauche', FALSE),
(38, 'Lame Sacro-Rectale', 'Sacro-Rectal Ligament', 'Postérolatéral gauche', 'Left posterolateral', 'image_fr/Lame_G.jpg', 'video_fr/parametre_PL.mp4', 'Profonde', TRUE, NULL, 'Postérolatéral droit', 'image_en/Lame_G.jpg', NULL, 'Lame.png', 'gauche', FALSE),
(33, 'LUS Distal', 'Distal LUS', 'Postérolatéral droit', 'Right posterolateral', 'image_fr/LUS_distal_D.jpg', 'video_fr/parametre_PL.mp4', 'Profonde', TRUE, 'Postérolatéral gauche', NULL, 'image_en/LUS_distal_D.jpg', NULL, 'LUS_distal.png', 'droite', FALSE),
(25, 'Espace Périvésical', 'Perivesical Space', 'Antérolatéral gauche', 'Left anterolateral', 'image_fr/Espace_perivesical_G.jpg', 'video_fr/perivesical.mp4', 'Profonde', TRUE, NULL, 'Antérolatéral droit', 'image_en/Espace_perivesical_G.jpg', NULL, 'Espace_perivesical.png', 'gauche', FALSE),
(54, 'Varices Pelviennes', 'Pelvic Congestion Syndrome', 'Pathologies associées', 'Associated pathologies', NULL, NULL, 'Profonde', NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE),
(55, 'Dilatation des Cavités Pyélocalicielles', 'Hydronephrosis', 'Pathologies associées', 'Associated pathologies', NULL, NULL, 'Profonde', NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE),
(37, 'LUS Distal', 'Distal LUS', 'Postérolatéral gauche', 'Left posterolateral', 'image_fr/LUS_distal_G.jpg', 'video_fr/parametre_PL.mp4', 'Profonde', TRUE, NULL, 'Postérolatéral droit', 'image_en/LUS_distal_G.jpg', NULL, 'LUS_distal.png', 'gauche', FALSE),
(28, 'Uretère', 'Ureter', 'Médiolatéral droit', 'Right mediolateral', 'image_fr/Uretere_DG.jpg', 'video_fr/uretere.mp4', 'Profonde', TRUE, 'Médiolatéral gauche', NULL, 'image_en/Uretere_DG.jpg', NULL, 'Ureter.png', 'droite', FALSE),
(51, 'Diaphragme', 'Diaphragm', 'Extrapelvien', 'Extrapelvic', 'image_fr/Diaphragme.jpg', 'video_fr/extra_pelvien.mp4', 'Profonde', FALSE, NULL, NULL, 'image_en/Diaphragme.jpg', NULL, NULL, NULL, TRUE),
(24, 'Ligament Rond Distal', 'Distal Round Ligament', 'Antérolatéral gauche', 'Left anterolateral', 'image_fr/Ligament_rond_G.jpg', 'video_fr/rond_distal.mp4', 'Profonde', TRUE, NULL, 'Antérolatéral droit', 'image_en/Ligament_rond_G.jpg', NULL, 'Ligament_rond_distal.png', 'gauche', FALSE),
(59, 'Malformation Utéro-Vaginale', 'Uterovaginal Malformation', 'Pathologies associées', 'Associated pathologies', NULL, NULL, 'Profonde', NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE),
(48, 'Uretère Lombaire', 'Lumbar Ureter', 'Extrapelvien', 'Extrapelvic', NULL, 'video_fr/extra_pelvien.mp4', 'Profonde', FALSE, NULL, NULL, NULL, NULL, 'Uretere_lombaire.png', NULL, TRUE),
(43, 'Torus/LUS Proximaux', 'Torus/Proximal Uterosacral Ligament (USL)', 'Médiocentral', 'Mediocentral', 'image_fr/TorusUSL_FR.jpg', 'video_fr/LUS.mp4', 'Profonde', FALSE, NULL, NULL, 'image_en/TorusUSL_EN.jpg', NULL, 'Lus_Proximal.png', NULL, TRUE),
(47, 'Paroi Abdominale / Région Inguinale', 'Abdominal Wall / Inguinal Region', 'Extrapelvien', 'Extrapelvic', 'image_fr/Paroi_abdominale.jpg', 'video_fr/extra_pelvien.mp4', 'Profonde', FALSE, NULL, NULL, 'image_en/Paroi_abdominale.jpg', NULL, NULL, NULL, TRUE),
(44, 'Rectum/Charnière Rectosigmoïdienne', 'Rectum / Rectosigmoid Junction', 'Postérocentral', 'Posterocentral', 'image_fr/rectumRS_FR.jpg', 'video_fr/CRV_Mesorectum.mp4', 'Profonde', FALSE, NULL, NULL, 'image_en/rectumRS_EN.jpg', NULL, 'Rectum.png', NULL, TRUE),
(46, 'Vessie', 'Bladder', 'Antérocentral', 'Anterocentral', 'image_fr/bladder.jpg', 'video_fr/vessie.mp4', 'Profonde', FALSE, NULL, NULL, 'image_en/bladder.jpg', NULL, NULL, NULL, TRUE),
(50, 'Cæcum – Iléon – Appendice – Sigmoïde', 'Caecum – Ileum – Appendix – Sigmoid Colon', 'Extrapelvien', 'Extrapelvic', 'image_fr/caecum_ileon_appendice.jpg', 'video_fr/extra_pelvien.mp4', 'Profonde', FALSE, NULL, NULL, 'image_en/caecum_ileon_appendice.jpg', NULL, NULL, NULL, TRUE),
(45, 'Ligament Rond Proximal', 'Proximal Round Ligament', 'Antérocentral', 'Anterocentral', 'image_fr/cl_prl.jpg', 'video_fr/rond_proximal.mp4', 'Profonde', FALSE, NULL, NULL, 'image_en/cl_prl.jpg', NULL, 'Ligament_rond_proximal.png', NULL, TRUE),
(49, 'Nerf Pudendal', 'Pudendal Nerve', 'Extrapelvien', 'Extrapelvic', 'image_fr/Nerf_pudendal.jpg', 'video_fr/extra_pelvien.mp4', 'Profonde', FALSE, NULL, NULL, 'image_en/Nerf_pudendal.jpg', NULL, NULL, NULL, TRUE);
