name: Build iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build web app
      run: npm run build
    
    - name: Install Capacitor CLI
      run: npm install -g @capacitor/cli
    
    - name: Sync Capacitor
      run: npx cap sync ios
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Build iOS (Archive)
      run: |
        cd ios/App
        xcodebuild archive \
          -workspace App.xcworkspace \
          -scheme App \
          -archivePath App.xcarchive \
          -configuration Release \
          CODE_SIGN_STYLE=Manual
    
    # Pour uploader vers App Store, ajoutez vos certificats dans GitHub Secrets
    # - name: Export & Upload to App Store
    #   env:
    #     APPLE_ID: ${{ secrets.APPLE_ID }}
    #     APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
    #   run: |
    #     # Commandes d'export et upload 